### ISSUE TITLE
Sluggish performance with just 5 task.

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-M11-2/main#144]
**Describe the bug**

As mention in the [DeveloperGuide](https://github.com/CS2113-AY1819S2-M11-2/main/blob/master/docs/DeveloperGuide.adoc#appendix-e-non-functional-requirements) of the group. 

```
Should be able to hold up to 250 tasks without a noticeable sluggishness in performance for typical usage.
```

There seem to be a sluggish performance when doing the following command
even though there is only 5 tasks.
* `list`
* `findpriority`
* `findname`

**To Reproduce**
1. `list`

1a1. `findpriority 1`

**Expected behavior**
Since there is only 5 task, I expect the find to be almost instance.

**Screenshots**
![slow-find](https://user-images.githubusercontent.com/2564679/55453983-a89f7a00-5610-11e9-902a-ffa0d5ea9770.gif)

<hr>

**Reported by:** @lycjackie
**Severity:** High

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#124]</sub>

**Comment by Justin-Ong** [comment]
I am unsure exactly what is causing this slowdown. Could be caused by list and find logic, could also be caused by the process that fills in the calendar. Unable to reproduce in my own testing (with 20 tasks in the list), perhaps need to test on older, slower hardware.

**Comment by lycjackie** [comment]
Hi, not sure exactly what is causing this but this issue was found toward the end of the dry run.

Perhaps, this might be occurring because of the long usage of the application?

Below are my computer OS and specs used for this testing. 

I hope these can provide some insights for the debugging.

OS: macOS mojave 10.14.4
Processor Name:	Intel Core i7
Processor Speed:	2.7 GHz
Number of Processors:	1
Total Number of Cores:4
L2 Cache (per Core):256 KB
L3 Cache:8 MB
Memory:16 GB

**Comment by Justin-Ong** [comment]
That is useful info, thank you.

That the issue only cropped up later broadens the scope, will have to look into history storage for undo/redo and possibly search for any memory leaks.

Will also try to test on similar specs to see if the issue can be replicated.

Thanks for the report.

**Comment by Justin-Ong** [comment]
Issue has been reproduced.

Steps:
1. Make a change to the task manager state (add, delete, etc)
2. Undo
3. Redo
4. Repeat steps 2 and 3
5. After several iterations of step 4, there will be a huge increase in memory usage (from ~300 MB to 1000+ MB in testing) and a significant slowdown of the app

This does not however actually help much with isolating the root cause of the issue. The increase in memory usage suggests a memory leak, but I can't find any in VersionedTaskManager or the calendar.

**Comment by Justin-Ong** [comment]
Unfortunately, this issue is not fixable within the time constraints. Closed.
